# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.config.os }}
    strategy:
      matrix:
        config:
        - os: ubuntu-latest
          vcpkg_triplet: x64-linux-dynamic
        - os: macos-latest
          vcpkg_triplet: arm64-osx-mixed
        - os: windows-latest
          vcpkg_triplet: x64-windows-mixed
    env:
      VCPKG_DISABLE_METRICS: 1

    steps:
      - uses: actions/checkout@v4

      # https://github.com/johnwason/vcpkg-action/blob/master/action.yml
      - name: checkout-vcpkg
        uses: actions/checkout@v3
        with:
          path: ${{ github.workspace }}/vcpkg
          repository: microsoft/vcpkg
          ref: '${{ steps.determine-checkout-revision.outputs.vcpkg-revision }}'
          fetch-depth: ${{ inputs.fetch-depth }}
        env:
          VCPKG_ROOT: "${{ github.workspace }}/vcpkg"
      - name: bootstrap-vcpkg-win
        if: runner.os == 'Windows'
        working-directory: ${{ github.workspace }}\vcpkg
        run: bootstrap-vcpkg.bat
        shell: cmd
        env:
          VCPKG_ROOT: "${{ github.workspace }}/vcpkg"
      - name: bootstrap-vcpkg-unix
        if: runner.os != 'Windows'
        working-directory: ${{ github.workspace }}/vcpkg
        run: ./bootstrap-vcpkg.sh
        shell: bash
        env:
          VCPKG_ROOT: "${{ github.workspace }}/vcpkg"
